---
name: hello-legacy-tomcat

releases:
- name: hello-legacy-tomcat
  version: 0.2
  url: https://github.com/making-dev/hello-legacy-tomcat-boshrelease/releases/download/0.2/hello-legacy-tomcat-0.2.tgz
  sha1: e5fd66efe3f8a41ae5b9be86081c48541ba5eb5b

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: hello-legacy-tomcat
  azs: [z1]
  instances: 1
  jobs:
  - name: hello-legacy-tomcat
    release: hello-legacy-tomcat
    properties: {}
  vm_type: default
  stemcell: ubuntu
  persistent_disk_type: default
  networks:
  - name: default
